### PR TITLE
A+C: add sbinet

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Review by cznic — APPROVED** [review]
LGTM, please commit to the master branch, thank you.

**Comment by sbinet** [comment]
added the little blurb to `doc.go`.
it's silent about all the changes that happened between `v1.1.0` (aka 7a63cd7) and now.

you probably have a better idea about what needs to be mentioned there?

**Review by cznic — APPROVED** [review]
LGTM. I think the addition to doc.go is complete enough.

Please commit to the master branch, thank you.

**Comment by cznic** [comment]
BTW, seems I've actually used tags before, just forgot about it completely. Or I'm confused by releases vs tags.

**Comment by cryptix** [comment]
> Or I'm confused by releases vs tags.

Github creates a tag on that commit when you make a release.

**Comment by sbinet** [comment]
yeah, github will do that for you (creating a tarball with the `vX.Y.Z` tag).

I don't have commit privileges to directly commit this to `origin/master` (so I don't think I can tag and push that tag to `origin` either) but I can push the "Merge pull request" button if you want :)

**Comment by sbinet** [comment]
(Strike that, I can...)

**Pull request merged**
