### PR TITLE
Add missing reserved keywords in doc. Closes #152

### LINKED ISSUE #152: `commit` cannot be used as an identifier
A column cannot be called `commit`, even though it's not a reserved keyword [according to the documentation](https://godoc.org/github.com/cznic/ql#hdr-Keywords).

```
ql "CREATE TABLE foo (commit string)"
2017/03/02 20:33:34 BEGIN TRANSACTION; CREATE TABLE foo (commit string); COMMIT;
2017/03/02 20:33:34 1:38 unexpected COMMIT, expected table column definition or identifier
```

### PR DESCRIPTION
**Pull request by boyvanduuren**
A few other keywords were missing as well. Went over the list, these are all of them.

### CODE REVIEW

**Comment by cznic** [comment]
@boyvanduuren Thank you for the PR! Please add yourself to the `AUTHORS` and/or `CONSTRIBUTORS` file(s). After that it's LGTM and you can merge by yourself.

Thanks again.

**Comment by boyvanduuren** [comment]
You're welcome! I can't merge this though, seems like I don't have write access.

**Comment by cznic** [comment]
> I can't merge this though, seems like I don't have write access.

You need to accept the collaborator's invite. Maybe check you spam folder ;-)

Please let me know if you cannot see it, I'll then merge the PR a we can figure out the missing invite later.

Can you see yourself [here](https://github.com/cznic/ql/settings/collaboration)?

**Comment by boyvanduuren** [comment]
Thought I had already accepted, guess I didn't! :)

**Pull request merged**
