### PR TITLE
Use the canonical import path for go4.org/lock

### PR DESCRIPTION
**Pull request by eliasnaur**

### CODE REVIEW

**Comment by cznic** [comment]
Thanks for the PR. However, it is in sort of conflict with #122 . I'm waiting for @onlyjob to review that branch. When it will be merged, this PR will become obsolete.

If this PR cannot wait for some reason, it *is* possible to merge it. It's effect will just vanish soon afterwards when #122 branch will be incorporated.

Let me know what's best for you, thanks.

**Comment by eliasnaur** [comment]
I have no problem waiting for #122.

**Comment by cznic** [comment]
Good, thank you.

**Comment by cznic** [comment]
#122 fixed. Closing, but thanks anyway!

**Pull request closed without merging**
