### PR TITLE
cache selectStmt inside where exists (select...)

### LINKED ISSUE #159: select in where exists (select...) must be evaluated only once.
Tracking issue for a missing optimization in #155 .

### PR DESCRIPTION
**Pull request by gernest**
Closes #159

Based on   #164 

Don't merge before #164

### CODE REVIEW

**Comment by gernest** [comment]
@cznic I have a question. 

If I submit a PR and It has been reviewed, should I wait for someone else to merge the PR? And what about the case when I want to squash the commits before merging?

**Comment by cznic** [comment]
If the review is an approval you can merge. Then the reviewer is to blame ;-)

**Comment by gernest** [comment]
😄  lol! Fair enough!

**Comment by cznic** [comment]
> And what about the case when I want to squash the commits before merging?

@gernest Forgot to answer this one, sorry. Please feel free to squash or not to squash on a per case basis and/or your personal preferences. Sometimes it's better to --squash, sometimes it's not, but you cannot make a really wrong decision either way.

(Eg. I'm used to making a lot of "noisy" commits on a dev branch, so a later --squash is often justified.)

**Pull request merged**
